# Day 02 Lab Log — Phase 2 Complete: Elastic SIEM, Fleet, Sysmon, Windows Telemetry, and Suricata IDS

**Phase Completed:** Phase 2 — Elastic SIEM + Windows Endpoint Telemetry + Suricata IDS
**Focus:** Elasticsearch, Kibana, Fleet Server, Elastic Agent, Sysmon, Windows Event Logs, Suricata IDS, Kibana Discover, Dashboards, Troubleshooting

---

## Purpose

Phase 1 built the virtual lab foundation — three networked VMs with a working host-only subnet and NAT internet access. Phase 2 turned that foundation into an actual working SIEM pipeline: Elasticsearch and Kibana for log storage and analysis, Fleet for centralized agent management, Elastic Agent + Sysmon for deep Windows endpoint telemetry, and Suricata for network-based IDS visibility.

## Lab Environment Used

- **Ubuntu-SIEM** — `192.168.56.112` (host-only) / `10.0.2.15` (NAT) — Ubuntu Server 24.04, 8GB RAM. Hosts Elasticsearch, Kibana, Fleet Server, and Suricata.
- **windows10victim** — `192.168.56.114` (host-only) — Windows 10 Pro, 4GB RAM. Enrolled as a Fleet-managed endpoint, running Elastic Agent + Sysmon.

(Full VM build details are in Day 01's log.)

## Tools Installed

- Elasticsearch 9.5.0
- Kibana 9.5.0
- Fleet Server (self-managed, running as an Elastic Agent on Ubuntu-SIEM)
- Elastic Agent 9.5.0 (Windows build, on windows10victim)
- Sysmon (SwiftOnSecurity configuration)
- Suricata 8.0.6 IDS (Emerging Threats Open ruleset)

---

## Elasticsearch Installation

Installed on Ubuntu-SIEM from the official Elastic APT repository (9.x branch), using the standard GPG key + `sources.list.d` pattern. Elastic's built-in security autoconfiguration handled TLS and the `elastic` superuser password automatically — no manual `elasticsearch.yml` editing was needed, since `http.host` defaults to `0.0.0.0` out of the box.

Verified with:

```bash
sudo curl --cacert /etc/elasticsearch/certs/http_ca.crt -u elastic:<password> https://192.168.56.112:9200
```

Returned a valid cluster JSON response ("You Know, for Search").

## Kibana Installation & Access

Installed from the same repository. Unlike Elasticsearch, Kibana does **not** auto-expose itself — `server.host` had to be changed from the default `localhost` to `0.0.0.0` in `/etc/kibana/kibana.yml` before it was reachable from a host-machine browser. Connected to Elasticsearch via an enrollment token + the browser-based enrollment/verification flow.

## Fleet Server Setup

Set up as a self-managed Fleet Server, running on Ubuntu-SIEM itself (no separate dedicated host, appropriate for a lab). Configured through Kibana's Fleet → Agents → Add Fleet Server → Quick Start wizard, which generated a service token and CA fingerprint, then installed via the Elastic Agent CLI with `--fleet-server-es`, `--fleet-server-policy`, `--fleet-server-port=8220`, and `--insecure` (required since Quick Start uses a self-signed cert).

## Windows Endpoint Enrollment + Sysmon

Enrolled windows10victim into Fleet under a new `windows-victim-policy`, using the Windows x86_64 Elastic Agent build and the enrollment command generated by Kibana (again with `--insecure`).

Sysmon was installed separately, outside of Fleet, using the well-known **SwiftOnSecurity** configuration:

```powershell
Invoke-WebRequest -Uri https://download.sysinternals.com/files/Sysmon.zip -OutFile Sysmon.zip
Invoke-WebRequest -Uri https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/master/sysmonconfig-export.xml -OutFile sysmonconfig-export.xml
.\Sysmon64.exe -accepteula -i sysmonconfig-export.xml
```

Confirmed locally via Event Viewer (`Applications and Services Logs > Microsoft > Windows > Sysmon > Operational`) before ever checking Kibana — a good habit for isolating "is the tool broken" from "is the pipeline broken."

To actually get Sysmon data into Elastic, a second Fleet integration was required: the dedicated **Windows** integration package (distinct from **System**, which only covers Security/Application/System event channels). Adding it with "Sysmon Operational" enabled unlocked the `windows.sysmon_operational` data stream.

## Suricata IDS Installation

Installed via the OISF stable PPA (`ppa:oisf/suricata-stable`), version 8.0.6. Configured to monitor the host-only interface (`enp0s8`) rather than the NAT interface, since that's the adapter that actually sees VM-to-VM lab traffic. `HOME_NET` set to the lab's `192.168.56.0/24` subnet. Pulled the Emerging Threats Open ruleset via `suricata-update` — 68,195 rules loaded, 52,254 enabled.

Validated locally: `eve.json` actively logging real flow/TLS/HTTP metadata (including JA3/JA4 fingerprints) for legitimate lab traffic — Elastic Agent talking to Elasticsearch, browser talking to Kibana. `fast.log` stayed empty, which is correct and expected — it only writes on an actual signature match, and nothing in normal lab traffic triggers the Emerging Threats ruleset. Per the roadmap, Suricata's role in Phase 2 is local validation only; shipping its logs into Elastic is a Phase 5 (Network Traffic Analysis) task.

## First Kibana Dashboard

Built and saved a 5-panel dashboard, **"Phase 2 - SOC Lab Overview,"** using Kibana Lens against the `logs-*` data view:

1. **Sysmon Event Volume Over Time** — line chart, event count over time
2. **Top Sysmon Event Codes** — bar chart; dominated by code 11 (FileCreate) and code 1 (Process Create), with 13 (Registry value set) and 3 (Network connection) also present
3. **Top Sysmon Processes** — bar chart on `process.name`; top hits included `mscorsvw.exe`, `svchost.exe`, `TiWorker.exe`
4. **Top Parent Processes** — bar chart on `process.parent.name`; `svchost.exe`, `services.exe`, and `smss.exe` led
5. **Sysmon Network Connections – Destination IP** — bar chart filtered to network-connection events only (`event.code:"3"`), since `destination.ip` is empty on non-network Sysmon events

---

## Troubleshooting Notes

Phase 2 had several real troubleshooting moments — each one traced to a root cause rather than patched around.

| Problem | What Was Checked | Root Cause | Fix |
|---|---|---|---|
| Kibana returned HTTP 503 "License information could not be obtained" right after setup | `journalctl -u kibana` | Missing Kibana saved-object encryption keys — the Debian package doesn't auto-generate them the way Elasticsearch auto-generates its security config. Kibana was stuck in a Fleet-setup retry loop; the 503 was a downstream symptom | Generated keys with `kibana-encryption-keys generate`, added the 3 lines to `kibana.yml`, restarted Kibana |
| Windows agent enrolled and showed `fleet: HEALTHY`, then flipped to Unhealthy — every data-shipping component failing with `dial tcp 10.0.2.15:9200 ... actively refused` | `elastic-agent status` on the Windows host | The Fleet Server install command's `--fleet-server-es=https://10.0.2.15:9200` auto-wrote a global default Fleet output in `kibana.yml`. That NAT-adapter IP was correct for Ubuntu-SIEM referring to itself, but Windows inherited the same output — and `10.0.2.15` on Windows resolves to *its own* NAT adapter, where nothing is listening | Fleet UI refused to edit the preconfigured output ("cannot be updated outside of kibana config file"), so the IP was corrected directly: `sed -i` on `xpack.fleet.outputs` in `kibana.yml`, then restart Kibana |
| After the output fix, most components went Healthy — but the agent's own self-monitoring components stayed stuck on the old IP | Kibana logs showed a "mismatched revisions" warning for the policy | Stale cached policy revision on the agent side | `Restart-Service "Elastic Agent"` on Windows forced a fresh policy pull (revision bumped 1 → 2), fully Healthy |
| Sysmon confirmed running locally (280+ events in Event Viewer), System integration confirmed shipping real Security/Application logs — but zero results querying for `Microsoft-Windows-Sysmon` | Discover, filtered by `event.provider` | Sysmon writes to its own separate event log channel (`Microsoft-Windows-Sysmon/Operational`), which the **System** integration does not collect | Added the separate **Windows** integration to the agent policy with "Sysmon Operational" enabled — no changes needed on the endpoint itself, the policy update deployed automatically |

**Lesson worth remembering:** any IP baked into a Fleet Server (or similar) CLI install command becomes a semi-permanent global default that *other* enrolled hosts inherit. Worth setting that to the host-only IP up front next time, even though the NAT IP is technically valid for the box installing it.

---

## What Phase 2 Proved

- A working Elastic Stack SIEM pipeline can be stood up end-to-end on a single Ubuntu VM: ingest, storage, and visualization all live together and talk to each other correctly.
- Fleet-managed agents introduce a layer of indirection (policies, outputs, integrations) that behaves differently from a standalone Beat — output config in particular is global-by-default in a way that isn't obvious until it breaks a *second* host.
- Sysmon and Windows' native Security/Application/System logs are genuinely separate pipelines under the hood, even though they both eventually land in the same Elasticsearch cluster. "The agent is healthy" and "the specific telemetry I want is flowing" are two different questions.
- Suricata can be fully installed, tuned, and validated without ever touching Elastic — network IDS and endpoint SIEM are complementary but independently operable tools.

## Skills Practiced

- Linux service management (`systemctl`, `journalctl`) as a first-line diagnostic tool
- Reading structured JSON logs (`eve.json`) and correlating them against known traffic
- Kibana Discover query construction — building filters from general to specific, catching field-name mismatches (`host.name` vs `host.hostname`) along the way
- Kibana Lens visualization building (axis/breakdown mechanics, field vs. quick-function config)
- Root-cause troubleshooting under a "verify before declaring done" discipline — every fix in this log was confirmed with a follow-up check, not assumed

---

## Checklist

- [x] Elasticsearch installed, secured, and verified
- [x] Kibana installed, exposed to the host browser, and verified
- [x] Fleet Server deployed and healthy
- [x] Windows endpoint enrolled and healthy
- [x] Sysmon installed with SwiftOnSecurity config, verified locally and in Elastic
- [x] Suricata installed, configured on the correct interface, and validated
- [x] First SOC dashboard built (5 panels) and saved to the Kibana library
- [x] All issues hit were root-caused and documented

---

## Summary

In Phase 2 of my SOC lab, I built a working Elastic-based SIEM pipeline from scratch: Elasticsearch and Kibana on the Ubuntu SIEM VM, a self-managed Fleet Server, and a Windows 10 endpoint enrolled with Elastic Agent and Sysmon for deep process, registry, and network telemetry. I validated ingestion in Kibana Discover, built a 5-panel dashboard covering event volume, top event codes, top processes, top parent processes, and network connections, and installed Suricata IDS for network-layer visibility.

Along the way I diagnosed and fixed four distinct real-world issues — missing Kibana encryption keys, a Fleet output pointing at the wrong network interface, a stale agent policy cache, and a missing Windows Event Log channel integration — each traced from symptom to root cause using logs and status commands rather than guesswork. Phase 2 transformed the lab from a set of connected VMs into a functioning, telemetry-producing SOC environment, ready for Phase 3.
